# Generated by Django 3.2 on 2023-06-10 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите, пожалуйста, название', max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(help_text='Введите цвет в формате RGB (#rrggbb)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#[a-fA-F0-9]{6}$', 'Используйте RGB-формат для указания цвета (#AABBCC)')], verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='Введите slug', max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
    ]
